    /**
     * Process items dari hasil API dengan semua data lengkap
     *
     * @param array $result
     * @param float $margin
     * @return array
     */
    private function processItems(array $result, float $margin): array
    {
        $items = [];
        $filename = $result['filename'] ?? 'unknown.pdf';
        $metadata = $result['metadata'] ?? [];
        
        // Extract invoice number dari metadata atau filename
        $invoiceNumber = $metadata['invoice_number'] ?? $this->extractInvoiceNumber($filename);
        
        foreach ($result['items'] as $item) {
            // Gunakan unit_price jika tersedia, fallback ke total
            $unitPrice = $item['unit_price'] ?? 0;
            $quantity = $item['quantity'] ?? 1;
            $buyPrice = $item['total'] ?? ($unitPrice * $quantity);
            
            // Hitung harga jual dengan margin
            $sellPrice = $buyPrice + ($buyPrice * $margin / 100);
            $profit = $sellPrice - $buyPrice;
            
            // Gunakan item_code dari PDF jika ada
            $itemCode = $item['item_code'] ?? null;
            if ($itemCode === '000000' || empty($itemCode)) {
                $itemCode = null; // Will be generated by system
            }

            $items[] = [
                'item' => [
                    'name' => $item['nama_barang'] ?? 'Unknown Item',
                    'item_code' => $itemCode,
                    'buy_price' => $buyPrice,
                    'margin' => $margin,
                    'sell_price' => $sellPrice,
                    'profit' => $profit,
                    'stock' => (int) $quantity, // Gunakan quantity dari PDF sebagai stock
                    'initial_stock' => (int) $quantity,
                    'unit_price' => $unitPrice,
                    'unit' => $item['unit'] ?? 'PCS',
                    'discount' => $item['discount'] ?? 0,
                    'original_tax_invoice_file_name' => $filename,
                    'tax_invoice_number' => $invoiceNumber,
                    'invoice_date' => $metadata['invoice_date'] ?? null,
                    'supplier_name' => $metadata['supplier_name'] ?? null,
                    'supplier_npwp' => $metadata['supplier_npwp'] ?? null,
                    'is_free_ppn' => false,
                ]
            ];
        }

        return $items;
    }
