#!/bin/bash

# Script untuk update CoretaxParserService.php di ASIK
# dengan fitur baru dari parser v2.0

ASIK_SERVICE="/Users/user/Project/ASIK/app/Services/CoretaxParserService.php"

echo "=================================================="
echo "🔧 Updating ASIK CoretaxParserService"
echo "=================================================="
echo ""

# Check if file exists
if [ ! -f "$ASIK_SERVICE" ]; then
    echo "❌ File not found: $ASIK_SERVICE"
    echo "Please make sure ASIK project exists at /Users/user/Project/ASIK"
    exit 1
fi

# Backup original file
BACKUP_FILE="${ASIK_SERVICE}.backup-$(date +%Y%m%d-%H%M%S)"
cp "$ASIK_SERVICE" "$BACKUP_FILE"
echo "✅ Backup created: $BACKUP_FILE"
echo ""

# Create the new processItems method
cat > /tmp/new_processItems.php << 'PHPEOF'
    /**
     * Process items dari hasil API dengan semua data lengkap
     *
     * @param array $result
     * @param float $margin
     * @return array
     */
    private function processItems(array $result, float $margin): array
    {
        $items = [];
        $filename = $result['filename'] ?? 'unknown.pdf';
        $metadata = $result['metadata'] ?? [];
        
        // Extract invoice number dari metadata atau filename
        $invoiceNumber = $metadata['invoice_number'] ?? $this->extractInvoiceNumber($filename);
        
        foreach ($result['items'] as $item) {
            // Gunakan unit_price jika tersedia, fallback ke total
            $unitPrice = $item['unit_price'] ?? 0;
            $quantity = $item['quantity'] ?? 1;
            $buyPrice = $item['total'] ?? ($unitPrice * $quantity);
            
            // Hitung harga jual dengan margin
            $sellPrice = $buyPrice + ($buyPrice * $margin / 100);
            $profit = $sellPrice - $buyPrice;
            
            // Gunakan item_code dari PDF jika ada
            $itemCode = $item['item_code'] ?? null;
            if ($itemCode === '000000' || empty($itemCode)) {
                $itemCode = null; // Will be generated by system
            }

            $items[] = [
                'item' => [
                    'name' => $item['nama_barang'] ?? 'Unknown Item',
                    'item_code' => $itemCode,
                    'buy_price' => $buyPrice,
                    'margin' => $margin,
                    'sell_price' => $sellPrice,
                    'profit' => $profit,
                    'stock' => (int) $quantity, // Gunakan quantity dari PDF sebagai stock
                    'initial_stock' => (int) $quantity,
                    'unit_price' => $unitPrice,
                    'unit' => $item['unit'] ?? 'PCS',
                    'discount' => $item['discount'] ?? 0,
                    'original_tax_invoice_file_name' => $filename,
                    'tax_invoice_number' => $invoiceNumber,
                    'invoice_date' => $metadata['invoice_date'] ?? null,
                    'supplier_name' => $metadata['supplier_name'] ?? null,
                    'supplier_npwp' => $metadata['supplier_npwp'] ?? null,
                    'is_free_ppn' => false,
                ]
            ];
        }

        return $items;
    }
PHPEOF

echo "📝 New processItems method created"
echo ""
echo "⚠️  Manual Update Required:"
echo "=================================================="
echo ""
echo "Please manually replace the processItems() method in:"
echo "$ASIK_SERVICE"
echo ""
echo "With the content from:"
echo "/tmp/new_processItems.php"
echo ""
echo "Or use this command to view the new method:"
echo "cat /tmp/new_processItems.php"
echo ""
echo "=================================================="
echo ""
echo "🔍 What's New:"
echo "  ✅ Stock now uses quantity from PDF (not default 1)"
echo "  ✅ Unit price extracted"
echo "  ✅ Unit/satuan tracked"
echo "  ✅ Discount amount saved"
echo "  ✅ Invoice metadata (date, supplier, etc.)"
echo "  ✅ Item code from PDF"
echo ""
echo "📖 See full documentation:"
echo "  - /Users/user/Project/CoretaxDataParser-API/PANDUAN_UPDATE_ASIK.md"
echo "  - /Users/user/Project/CoretaxDataParser-API/QUICK_REFERENCE.md"
echo ""
echo "Backup saved at: $BACKUP_FILE"
